// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - ragu               v1.0.0
// source: github.com/rancher/opni/plugins/logging/pkg/apis/aiadmin/aiadmin.proto

package aiadmin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AIAdminClient is the client API for AIAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIAdminClient interface {
	GetPretrainedModel(ctx context.Context, in *PretrainedModelRef, opts ...grpc.CallOption) (*PretrainedModel, error)
	PutPretrainedModel(ctx context.Context, in *PretrainedModel, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type aIAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAdminClient(cc grpc.ClientConnInterface) AIAdminClient {
	return &aIAdminClient{cc}
}

func (c *aIAdminClient) GetPretrainedModel(ctx context.Context, in *PretrainedModelRef, opts ...grpc.CallOption) (*PretrainedModel, error) {
	out := new(PretrainedModel)
	err := c.cc.Invoke(ctx, "/aiadmin.AIAdmin/GetPretrainedModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAdminClient) PutPretrainedModel(ctx context.Context, in *PretrainedModel, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aiadmin.AIAdmin/PutPretrainedModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAdminServer is the server API for AIAdmin service.
// All implementations must embed UnimplementedAIAdminServer
// for forward compatibility
type AIAdminServer interface {
	GetPretrainedModel(context.Context, *PretrainedModelRef) (*PretrainedModel, error)
	PutPretrainedModel(context.Context, *PretrainedModel) (*emptypb.Empty, error)
	mustEmbedUnimplementedAIAdminServer()
}

// UnimplementedAIAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAIAdminServer struct {
}

func (UnimplementedAIAdminServer) GetPretrainedModel(context.Context, *PretrainedModelRef) (*PretrainedModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPretrainedModel not implemented")
}
func (UnimplementedAIAdminServer) PutPretrainedModel(context.Context, *PretrainedModel) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPretrainedModel not implemented")
}
func (UnimplementedAIAdminServer) mustEmbedUnimplementedAIAdminServer() {}

// UnsafeAIAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAdminServer will
// result in compilation errors.
type UnsafeAIAdminServer interface {
	mustEmbedUnimplementedAIAdminServer()
}

func RegisterAIAdminServer(s grpc.ServiceRegistrar, srv AIAdminServer) {
	s.RegisterService(&AIAdmin_ServiceDesc, srv)
}

func _AIAdmin_GetPretrainedModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PretrainedModelRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdminServer).GetPretrainedModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiadmin.AIAdmin/GetPretrainedModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdminServer).GetPretrainedModel(ctx, req.(*PretrainedModelRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAdmin_PutPretrainedModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PretrainedModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAdminServer).PutPretrainedModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aiadmin.AIAdmin/PutPretrainedModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAdminServer).PutPretrainedModel(ctx, req.(*PretrainedModel))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAdmin_ServiceDesc is the grpc.ServiceDesc for AIAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiadmin.AIAdmin",
	HandlerType: (*AIAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPretrainedModel",
			Handler:    _AIAdmin_GetPretrainedModel_Handler,
		},
		{
			MethodName: "PutPretrainedModel",
			Handler:    _AIAdmin_PutPretrainedModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/rancher/opni/plugins/logging/pkg/apis/aiadmin/aiadmin.proto",
}
