{{- if .Values.gateway.enabled }}
apiVersion: opni.io/v1beta2
kind: Gateway
metadata:
  name: opni-gateway
  namespace: {{ include "opni.namespace" . }}
  labels:
    {{- include "opni.labels" . | nindent 4 }}
spec:
  hostname: {{ .Values.gateway.hostname }}
  serviceType: {{ .Values.gateway.serviceType }}
  {{- with .Values.gateway.serviceAnnotations }}
  serviceAnnotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.auth }}
  auth:
    provider: {{ .provider }}
    {{- if eq .provider "openid" }}
    openid: {{ toYaml .openid | nindent 6 }}
    {{- end }}
  {{- end}}
    {{- if eq .Values.gateway.auth.provider "noauth" }}
    noauth:
      grafanaHostname: {{ .Values.monitoring.grafana.hostname }}
    {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.extraVolumeMounts }}
  extraVolumeMounts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}