# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opniclusters.opni.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: replace-me
          name: opni-webhook
          path: /convert
      conversionReviewVersions:
      - v1beta1
      - v1beta2
