{{- if ( and .Values.logging.enabled .Values.logging.opensearch.exposeDataNodes.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  name: expose-data-nodes
  labels:
    opster.io/opensearch-cluster: opni
    opster.io/opensearch-nodepool: nodes
spec:
  ports:
  - name: node-web
    port: 9200
    targetPort: 9200
  selector:
    opster.io/opensearch-cluster: opni
    opster.io/opensearch-nodepool: nodes
  type: {{ .Values.logging.opensearch.exposeDataNodes.serviceType }}
{{- end }}