{{- if .Values.ai.enabled }}
apiVersion: opni.io/v1beta2
kind: PretrainedModel
metadata:
  name: longhorn
  namespace: {{ include "opni.namespace" . }}
  labels:
    {{- include "opni.labels" . | nindent 4 }}
spec:
  replicas: 1
  source:
    http:
      url: "https://opni-public.s3.us-east-2.amazonaws.com/pretrain-models/longhorn-model-v0.6.0.zip"
  hyperparameters:
    modelThreshold: "0.7"
    minLogTokens: 1
    serviceType: "longhorn"
{{- end }}